language: python
branches:
    only:
      - master
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r django_requirements.txt
  - pip install coveralls
script:
  - make test doc quality
after_success:
  - coveralls
